version: '3.7'

services:
  api:
    build: ./Api
    env_file: 
      - ./Api/.env
    volumes:
      - ./Api:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - '3000:3000'
  vaske_app:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.development.local
    volumes:
      - './frontend:/app/'
      - '/app/node_modules'
    ports:
      - '8081:8080'
